In [2]:
import copy
import numpy as np
puzzle1= [[0, 4, 0, 0, 0, 0, 1, 7, 9], 
[0, 0, 2, 0, 0, 8, 0, 5, 4], 
[0, 0, 6, 0, 0, 5, 0, 0, 8], 
[0, 8, 0, 0, 7, 0, 9, 1, 0], 
[0, 5, 0, 0, 9, 0, 0, 3, 0], 
[0, 1, 9, 0, 6, 0, 0, 4, 0], 
[3, 0, 0, 4, 0, 0, 7, 0, 0], 
[5, 7, 0, 1, 0, 0, 2, 0, 0], 
[9, 2, 8, 0, 0, 0, 0, 6, 0]] 

puzzle2 =    [[5,3,0,0,7,0,0,0,0],
     [6,0,0,1,9,5,0,0,0],
     [0,9,8,0,0,0,0,6,0],
     [8,0,0,0,6,0,0,0,3],
     [4,0,0,8,0,3,0,0,1],
     [7,0,0,0,2,0,0,0,6],
     [0,6,0,0,0,0,2,8,0],
     [0,0,0,4,1,9,0,0,5],
     [0,0,0,0,8,0,0,7,9]]
puzzle = puzzle2


In [3]:
def isPossible(row,char, n):
    global puzzle

     #Get Lists
    def get_row(row,puzzle):
      l = puzzle[row]
      return l
    def get_col(char,puzzle):
      l = list()
      for row in range(len(puzzle)):
        l.append(puzzle[row][char])
      return l
    def get_square(row,char,puzzle):
      #The suduko is divided into 9 sub squares (3 sub x and 3 y)
      sub_x = int(char/3)
      sub_y = int(row / 3)
      subs = {0:[0,1,2],1:[3,4,5],2:[6,7,8]}
      res = list()
      for row in subs[sub_y]:
        for char in subs[sub_x]:
          # print(row,char)
          res.append(puzzle[row][char])
      return res

    def findCandidates(l):
      full = [1,2,3,4,5,6,7,8,9]
      return  list(filter(lambda x: x not in l, full))
      r1 = puzzle[quad_row][quad_char:quad_char+3]
      r2 = puzzle[quad_row+1][quad_char:quad_char+3] + r1
      l = puzzle[quad_row+2][quad_char:quad_char+3] + r2
      return l
    def consolidateLists(get_row,get_col,get_square):
      get_row.extend(get_col)
      get_row.extend(get_square)
      res = set(get_row)
      return res

    row_nbrs = list(set(get_row(row,puzzle)))
    col_nbrs = list(set(get_col(char,puzzle)))
    square_nbrs = list(set(get_square(row,char,puzzle)))
    all_nbrs = consolidateLists(row_nbrs,col_nbrs,square_nbrs)
    items_outstanding = findCandidates(all_nbrs)
    # print(items_outstanding)
    return True if n in items_outstanding else False

In [31]:
row = 0
char = 0
print(isPossible(row,char,7))

False


In [32]:
def solver():
    global puzzle
    for row in range(9):
        for char in range(9):
            if puzzle[row][char] == 0:
                for n in range(1,10):
                    if isPossible(row,char,n):
                        puzzle[row][char] = n
                        solver()
                        # if solver cannot keep going
                        puzzle[row][char] = 0
                return 
    print(np.matrix(puzzle))
 

In [34]:
solver()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [ ]:
print('hi')

In [1]:
print("hi")

hi
